In [3]:
from matplotlib.image import imread
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [4]:
im_small = imread('C:/data/CS229/ps3/mandrill-small.tiff')
X = im_small.reshape(-1,3)
X.shape
num_clusters = 16
_idxes = np.random.choice(np.arange(X.shape[0]), size=num_clusters, replace=False)
centroids = X[_idxes]
print('centroids data type')
print(centroids.dtype)
print('X data type')
print(X.dtype)
print('####### a simple test')
print('X[4]')
print(X[4])
print('centroids[0]')
print(centroids[0])
print('X[4]-centroids[0]')
print(X[4]-centroids[0])

centroids data type
uint8
X data type
uint8
####### a simple test
X[4]
[135 126  55]
centroids[0]
[116 149 117]
X[4]-centroids[0]
[ 19 233 194]
